# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QColorDialog
from PyQt5.QtCore import Qt
from manager import Manager
import os
import cv2


class Ui_MainWindow(object):

    def __init__(self):
        self.manager = Manager()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelImg = QtWidgets.QLabel(self.centralwidget)
        self.labelImg.setText("")
        self.labelImg.setObjectName("labelImg")
        self.labelImg.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_2.addWidget(self.labelImg)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelLayout = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.labelLayout.setFont(font)
        self.labelLayout.setObjectName("labelLayout")
        self.gridLayout.addWidget(self.labelLayout, 0, 0, 1, 1)
        self.labelLayoutUrl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.labelLayoutUrl.setFont(font)
        self.labelLayoutUrl.setObjectName("labelLayoutUrl")
        self.gridLayout.addWidget(self.labelLayoutUrl, 0, 1, 1, 1)
        self.pushButtonLayout = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonLayout.setFont(font)
        self.pushButtonLayout.setObjectName("pushButtonLayout")
        self.gridLayout.addWidget(self.pushButtonLayout, 1, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 40)
        self.gridLayout.setColumnStretch(1, 60)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelLogo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.labelLogo.setFont(font)
        self.labelLogo.setObjectName("labelLogo")
        self.gridLayout_2.addWidget(self.labelLogo, 0, 0, 1, 1)
        self.labelLogoUrl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.labelLogoUrl.setFont(font)
        self.labelLogoUrl.setObjectName("labelLogoUrl")
        self.gridLayout_2.addWidget(self.labelLogoUrl, 0, 1, 1, 1)
        self.pushButtonLogo = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonLogo.setFont(font)
        self.pushButtonLogo.setObjectName("pushButtonLogo")
        self.gridLayout_2.addWidget(self.pushButtonLogo, 1, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 2, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 40)
        self.gridLayout_2.setColumnStretch(1, 60)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelCorLogo1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.labelCorLogo1.setFont(font)
        self.labelCorLogo1.setObjectName("labelCorLogo1")
        self.gridLayout_3.addWidget(self.labelCorLogo1, 0, 0, 1, 1)
        self.labelCorLogo1Cor = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.labelCorLogo1Cor.setFont(font)
        self.labelCorLogo1Cor.setObjectName("labelCorLogo1Cor")
        self.gridLayout_3.addWidget(self.labelCorLogo1Cor, 0, 1, 1, 1)
        self.pushButtonCorLogo1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCorLogo1.setFont(font)
        self.pushButtonCorLogo1.setObjectName("pushButtonCorLogo1")
        self.gridLayout_3.addWidget(self.pushButtonCorLogo1, 1, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 2, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 40)
        self.gridLayout_3.setColumnStretch(1, 60)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelCorLogo2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.labelCorLogo2.setFont(font)
        self.labelCorLogo2.setObjectName("labelCorLogo2")
        self.gridLayout_4.addWidget(self.labelCorLogo2, 0, 0, 1, 1)
        self.labelCorLogo2Cor = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.labelCorLogo2Cor.setFont(font)
        self.labelCorLogo2Cor.setObjectName("labelCorLogo2Cor")
        self.gridLayout_4.addWidget(self.labelCorLogo2Cor, 0, 1, 1, 1)
        self.pushButtonCorLogo2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCorLogo2.setFont(font)
        self.pushButtonCorLogo2.setObjectName("pushButtonCorLogo2")
        self.gridLayout_4.addWidget(self.pushButtonCorLogo2, 1, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 2, 0, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 40)
        self.gridLayout_4.setColumnStretch(1, 60)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButtonDownload = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonDownload.setFont(font)
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.verticalLayout.addWidget(self.pushButtonDownload)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 60)
        self.horizontalLayout_2.setStretch(1, 40)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButtonLayout.clicked.connect(
            lambda: self.openFile('pushButtonLayout'))
        self.pushButtonLogo.clicked.connect(
            lambda: self.openFile('pushButtonLogo'))
        self.pushButtonCorLogo1.clicked.connect(
            lambda: self.openColorPicker('pushButtonCorLogo1'))
        self.pushButtonCorLogo2.clicked.connect(
            lambda: self.openColorPicker('pushButtonCorLogo2'))
        self.pushButtonDownload.clicked.connect(self.saveCombinedImg)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Seu Boné Workbench"))
        self.labelLayout.setText(_translate("MainWindow", "Layout:"))
        self.labelLayoutUrl.setText(_translate("MainWindow", "url"))
        self.pushButtonLayout.setText(
            _translate("MainWindow", "Adicionar Layout"))
        self.labelLogo.setText(_translate("MainWindow", "Logo:"))
        self.labelLogoUrl.setText(_translate("MainWindow", "url"))
        self.pushButtonLogo.setText(_translate("MainWindow", "Adicionar Logo"))
        self.labelCorLogo1.setText(_translate("MainWindow", "Cor Logo 1:"))
        self.labelCorLogo1Cor.setText(_translate("MainWindow", "Default"))
        self.pushButtonCorLogo1.setText(
            _translate("MainWindow", "Escolher Cor Logo 1"))
        self.labelCorLogo2.setText(_translate("MainWindow", "Cor Logo 2:"))
        self.labelCorLogo2Cor.setText(_translate("MainWindow", "Default"))
        self.pushButtonCorLogo2.setText(
            _translate("MainWindow", "Escolher Cor Logo 2"))
        self.pushButtonDownload.setText(_translate("MainWindow", "Baixar "))

    def openFile(self, buttonId):
        fname, _ = QFileDialog.getOpenFileName(
            self.centralwidget, 'Abrir Arquivo', os.getcwd(), 'Images (*.png *.jpg *.jpeg)')
        if (fname):
            if (buttonId == 'pushButtonLayout'):
                self.manager.setLayoutUrl(fname)
                self.labelLayoutUrl.setText('.../'+fname.split("/")[-1])
                self.manager.setLayoutUrl(fname)
                if (self.manager.validate()):
                    self.loadImage(QtGui.QPixmap(self.manager.update()))
                else:
                    self.loadImage(QtGui.QPixmap(fname))
            else:
                self.manager.setLogoUrl(fname)
                self.manager.cleanLogo()
                self.labelLogoUrl.setText('.../'+fname.split("/")[-1])
                if (self.manager.validate()):
                    self.loadImage(QtGui.QPixmap(self.manager.update()))

    def openColorPicker(self, buttonId):
        color = QColorDialog.getColor()
        if color.isValid():
            if (buttonId == 'pushButtonCorLogo1'):
                self.manager.setColor1(color.name())
                self.labelCorLogo1Cor.setText(color.name())
                self.labelCorLogo1Cor.setStyleSheet(
                    f"background-color: {color.name()};")
                if (self.manager.validate()):
                    self.loadImage(QtGui.QPixmap(self.manager.update()))

            else:
                self.manager.setColor2(color.name())
                self.labelCorLogo2Cor.setText(color.name())
                self.labelCorLogo2Cor.setStyleSheet(
                    f"background-color: {color.name()};")
                if (self.manager.validate()):
                    self.loadImage(QtGui.QPixmap(self.manager.update()))

    def loadImage(self, pixmap):
        self.labelImg.setPixmap(pixmap.scaled(
            self.labelImg.width(), self.labelImg.height(), Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation))

    def saveCombinedImg(self):
        '''if fpath:
            print(fpath)'''
        if self.manager.validate():
            fpath = QtWidgets.QFileDialog.getExistingDirectory(self.centralwidget, 'Selecione pasta')
            if fpath:
                temp = cv2.imread('combined.png')
                cv2.imwrite(fpath+'/combined.png', temp)

    def showManagerStats(self):
        print(f'\nLayout URL = {self.manager.getLayoutUrl()}\nLogo URL = {self.manager.getLogoUrl()}\nCor 1 = {self.manager.getColor1()}\nCor 2 = {self.manager.getColor2()}')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
